title: Super Title
author: GitHub User
email: layne1990@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a short description

# social links
twitter_username: your-twitter-handle
github_username:  layne1990

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
